DROP TABLE IF EXISTS InitialProviders;
DROP TABLE IF EXISTS ActionProviders;

CREATE TABLE IF NOT EXISTS ActionProviders (
    ProviderId INTEGER PRIMARY KEY AUTOINCREMENT,
    Label TEXT NOT NULL,
    Homepage TEXT NOT NULL,
    Icon TEXT NOT NULL,
    Tag TEXT NOT NULL,
    Link TEXT NOT NULL,
    ObsoleteCount INTEGER DEFAULT 0,
    UsageCount INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS InitialProviders (
    ProviderId INTEGER PRIMARY KEY,
    Enabled INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (ProviderId) REFERENCES ActionProviders(ProviderId) ON DELETE CASCADE
);